### ISSUE TITLE
Allow to sort sets in matrix

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/upset2#10]
The sets currently visible in the upset plots (the columns of the matrix) should be sortable. 

- [ ] by size
- [ ]  alphabetical 
- [ ] manual (drag and drop) 

This should work through a context-menu on a "Sets" label.

**Comment by JakeWags** [comment]
Closed by #138 

Drag & Drop should be implemented after #110 since the vertical layout will make the list sorting function simpler.
Issue created for drag & drop: #137
