### ISSUE TITLE
Context Menu for Sets

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/upset2#113]
The sets should have a context menu, revealed on right-click. 

Two options: 
* Remove
* Bring "Setname" to top

**Comment by JakeWags** [comment]
@alexsb could you clarify what "Bring 'Setname' to top" is supposed to do?

**Comment by alexsb** [comment]
This is sorted by setnames, so that "Fruit" is at the top.

<img width="928" alt="image" src="https://user-images.githubusercontent.com/2039375/219804502-e04b623d-7c6f-4457-abde-b7cd7cb95ed7.png">

**Comment by JakeWags** [comment]
So then we also need to add sort by specific set, correct?

**Comment by alexsb** [comment]
The set to sort by is specified by right-clicking on it (or clicking in the case of UpSet 1). There shouldn't be a global "sort by specific set" option. That mostly exists because "sort by degree" isn't otherwise possible.

**Comment by JakeWags** [comment]
Issue for "Bring Set to Top" sorting: #146
