### ISSUE TITLE
Update handling of "Unused Sets"

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/upset2#114]
For this here: 
<img width="627" alt="image" src="https://user-images.githubusercontent.com/2039375/219228633-844896d5-ebda-4a71-b435-09666e4f071b.png">

* Remove the Sort Sets Button
* Add a vertical label called "Unused Sets"  (should look like the sets label described in #110)
* Add the sort functionality to the context menu for the label

**Comment by JakeWags** [comment]
@alexsb Could you clarify the styling for the "Unused Sets" label? Do you still want to display all the unused sets?

**Comment by alexsb** [comment]
Here's a design: 

<img width="774" alt="image" src="https://user-images.githubusercontent.com/2039375/220452654-37cfefcd-ef15-4f4b-b635-a7724325640d.png">

https://www.figma.com/file/O031Jl2qjDIyCfb66Z01Qp/UpSet-Set-Menu?node-id=0%3A1&t=Jgx1ssgBBLIIBVnj-0 

Notes: 

* The active set bars are darker and have the label seprately
* The active set bars show the size in the bar, with a smaller non-bold font. 
* The set bar font color adapts to the background 
* The inactive set bar font is not bold
* All labels use proper ellipsis to truncate the label 
* A tool-tip is provided for all bars
* Elements can be added or removed via context menu
