### ISSUE TITLE
UpSetJS server getting stuck after data load

### ISSUE THREAD

**Issue by wowrao101** [visdesignlab/upset2#197]
Hello, I have setup the UpSetJS server locally and am able to load toy datasets, however when I try adding my original dataset (that is significantly bigger than the toy datasets), I get the following issue in ```multinet-api```, 

```
multinet-api-arangodb-1  | 2023-06-23T04:47:37Z [1] WARNING [8bcee] {queries} slow query: 'FOR doc IN (FOR doc in @@coll0 RETURN doc) LIMIT 0, 9007199254740991 RETURN doc', bind vars: {"@coll0":"fullDataFrame"}, database: w-df4030b001364e88b04b451717af9c28, user: readonly, id: 1324257, token: QRY1324257, exit code: 0, took: 11.023005 s
```

i am assuming this is because the computations required are much more for the dataset, however I wanted to see if there were any alternatives to optimize for the same. 

Thanks

**Comment by JakeWags** [comment]
@wowrao101 That looks like a warning, so shouldn't cause issues with the loading. Are you able to load the data at all?
What are the dimensions of your dataset? If you are willing to provide it, I can try loading the dataset on my machine.

**Comment by JakeWags** [comment]
Closing due to non-activity
