### ISSUE TITLE
Improve boxplots for subset and aggregate rows

### ISSUE THREAD

**Issue by JakeWags** [visdesignlab/upset2#203]
Depends #201 

<= 10 data points: strip plot with mean
more than 10 data points: overlaid strip plot with KDE or violin with "lightning" (encoded data such as mean)

**Comment by JakeWags** [comment]
Options to switch between plot types

**Comment by alexsb** [comment]
I'm closing this as the dot-plots are implemented and the violin plots should go into its own ticket.
