### ISSUE TITLE
Implement Brushing from table and element view to intersection view 

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/upset2#24]
I want to select one or multiple items in any view and see where they are in the intersections.

**Comment by JakeWags** [comment]
See #253

**Comment by NateLanza** [comment]
- Standard Vega brushing (rectangular)
- Should occur in the existing plot
- Backselection should show a size bar in each row showing the number of elements selected by the brush
- Selection should be trracked
- Query table should only show elements that have been brushed
- There should be an "All Items" query that's persistent but can be bookmarked or unbookmarked at all times

**Comment by NateLanza** [comment]
Brushes should be saved as element queries and selectable/bookmarkable in that view. When brushing, all elements that aren't selected in plots should grey out, and selected elements should get the brush color. Bookmark and selection format will have to change to accommodate element selections.
