### ISSUE TITLE
Captioning

### ISSUE THREAD

**Issue by JakeWags** [visdesignlab/upset2#240]
auto-generated caption based on alt-txt api call
user created caption

Caption for everybody + image description for low-vision users

**Comment by JakeWags** [comment]
Alt text generation is done. What remains is a user editable caption field option. This could also manifest as an edit option on the alt-text itself.

The result will need to be saved in the provenance state, so multinet can register this.

**Comment by NateLanza** [comment]
More detail:
- User can edit alttxt pane with their own custom caption
- Custom caption should be exported in the grammar
- Custom caption should be a trrack action/saved in multinet state (these go together)
AND/OR
- Have a user caption field that doesn't affect the alttxt (needs to be discussed in meeting)

**Comment by NateLanza** [comment]
Plan A, which I'm starting on, is to implement this as an editable alttxt. If the plot changes in a way that affects the alttxt while the alttxt has already been edited by the user, a prompt will pop-up asking the user if they'd like to regenerate the alttxt with the new changes. Regenerating will stash the previous user caption and show a prompt to go back to that. That will be concurrent with a new "regenerate alttxt" prompt if the plot again changes meaningfully. The most recent custom caption will be exported in the grammar.

**Comment by NateLanza** [comment]
Don't implement too much logic yet for user vs autogenerated alttxts. This needs a follow-up issue to implement "git merge"-esque logic to try and merge the user edits with new API generations.

**Comment by NateLanza** [comment]
Notes from meeting 5/2/24:
- Editing the caption makes locks the alttxt. Unlocking discards the changes; use a lock icon
- Rename 'alt-text' tab to 'text' or 'text description'
- Top of alttxt pane should be 'Title: [user entry]'
- Then, 'Caption: [user entry]'
- Then, 'Text Description: [user entry]'
- Show toggle button for short vs long description
- "Provide plot information" link at the bottom, pops up a modal, instead of the plot information dropdown

**Comment by NateLanza** [comment]
5/16/24
- Title, caption, authors, plot information at top. Should all display congruently with an edit icon to modify all at the same time. 
    - X icon needs to not be inline with title
    - Save button for everything at the same time
        - Bundle caption, title, authors into plotinformation & have only one action
    - Caption & authors should support markdown
    - Divider should be 100% width
    - Everything should autosave after 5s of not editing
- Desc: have toggle for manual only and make visually congruent with the long description toggle. Have separate short and long user alttexts

**Comment by NateLanza** [comment]
Notes from meeting 6/11/24
- Preview plotinformation text
- Store edits when manual editing is turned off
- Reset to automatic button
