### ISSUE TITLE
Add alternative visual encodings for attributes

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/upset2#249]
Box-plots are an OK option, but we should add three more: 

* A violin plot that also shows the median and the IQR; with the low-number dot-plot option
* Just a strip plot 
* The jittered dot-plot

**Comment by JakeWags** [comment]
Would there be a context menu option to change the plot, or did you have something else in mind?

**Comment by alexsb** [comment]
Yes, from the menu bar where you can sort and remove the col

**Comment by JakeWags** [comment]
Maintain jittered dot plot for less than 5. Potentially use d3 for these
