### ISSUE TITLE
Make upset usable as a module in other tools

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/upset2#25]
We want to make it possible that upset can be easily integrated into other tools. 

Probably an npm approach is best. 

To do that, we want to expose the following things as a public API: 

 * Data loading
 * Adding/removing sets (in/out)
 * Selections and brushes (in/out) 

It should also be configurable, which components should be included.

**Comment by JakeWags** [comment]
This will need to be re-addressed with the migration to multinet. UpSet as a react component should take in data required, but this should be tested
