### ISSUE TITLE
Why I can not install upset2-react

### ISSUE THREAD

**Issue by xiyeheng** [visdesignlab/upset2#369]
I did the npm install following the instruction, but I got this, how can I resolve it?
<img width="855" alt="image" src="https://github.com/user-attachments/assets/8d13166e-0be3-4b3d-960f-c62b7279a9f0">

**Comment by JakeWags** [comment]
Apologies, we have a large feature in the works (see #370) and since this will be adding a breaking change to the config, we are waiting to release 1.0 of the NPM package before this feature is completed. I will note this in the README document.
