### ISSUE TITLE
Provide help options for menu items

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/upset2#39]
Using a question mark and the help text on hover: 
![image](https://user-images.githubusercontent.com/2039375/56693951-dd986d00-66a2-11e9-9f69-34d21d2d42df.png)

**Comment by alexsb** [comment]
This icon (no circle) is probably good: 

https://fontawesome.com/icons/question?style=solid

**Comment by JakeWags** [comment]
@alexsb Should this be on every aggregation option (for example) or just the accordion header?

**Comment by alexsb** [comment]
It probably makes sense for each option, as the options aren't easily understood, no?
