### ISSUE TITLE
Show selections in set view

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/upset2#44]
Here's a good approach implemented in the original UpSet: 

![image](https://user-images.githubusercontent.com/2039375/82583484-4d9c4f80-9b50-11ea-8965-94a3d7cae8e4.png)

**Comment by JakeWags** [comment]
Looks like this has been implemented.
![image](https://user-images.githubusercontent.com/35744963/215615333-163cf6f6-2736-43ed-b899-d06ccfff524a.png)
In this screenshot, `Three` is selected and the sidebar shows it with a darker background.
